name: ubuntu

on:
  pull_request:

  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [3.4.1]

    env:
      BUNDLE_PATH: .bundle

    steps:
      - uses: actions/checkout@v2

      - name: Setup ruby
        uses: eregon/use-ruby-action@master
        with:
          ruby-version: ${{ matrix.ruby }}

      - uses: actions/cache@v4
        with:
          path: ${{ env.BUNDLE_PATH }}
          key: dependencies-${{ hashFiles('Gemfile.lock') }}
          restore-keys: dependencies-

      - name: Install dependencies
        run: |
          gem install bundler -v 2.3.20
          bundle install --jobs 3 --retry 3

      - name: Run tests
        run: RUBYOPT="-E UTF-8" bundle exec rake
